palette = "dracula"

format = """
[](navy)\
$os\
$username\
[](bg:red fg:navy)\
$directory\
[](fg:red bg:orange)\
$git_branch\
$git_status\
[](fg:orange bg:cyan)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:cyan bg:purple)\
$time\
[ ](fg:purple)
$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:navy fg:beige"
style_root = "bg:navy fg:beige"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:navy"
disabled = true # Disabled by default

[directory]
style = "bg:red fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Development" = "󰈮"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:orange fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:orange fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:purple fg:black"
format = '[  $time ]($style)'

[palettes.dracula]
black = "#282A36"
gray = "#44475A"
beige = "#F8F8F2"
navy = "#6272A4"
cyan = "#8BE9FD"
green = "#50FA7B"
orange = "#FFB86C"
pink = "#FF79C6"
purple = "#BD93F9"
red = "#FF5555"
yellow = "#F1FA8C"
